// <auto-generated />
using System;
using EventSourcR.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventSourcR.EntityFrameworkCore.SqlServer.Migrations
{
    [DbContext(typeof(EventStore))]
    [Migration("20190106015847_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.18572.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventSourcR.EntityFrameworkCore.RecordedEventEntity", b =>
                {
                    b.Property<long>("EventNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AggregateId");

                    b.Property<string>("AggregateType");

                    b.Property<long>("AggregateVersion");

                    b.Property<Guid>("EventId");

                    b.Property<string>("EventType");

                    b.Property<DateTimeOffset>("Recorded");

                    b.Property<string>("SerializedData");

                    b.Property<string>("SerializedMetadata");

                    b.HasKey("EventNumber");

                    b.HasAlternateKey("EventId");

                    b.HasAlternateKey("AggregateId", "AggregateVersion");

                    b.HasIndex("AggregateId");

                    b.HasIndex("AggregateType");

                    b.HasIndex("EventType");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
